# Listening port
port: 8182

# Logs directory
logpath: "./logs"

# MongoDB for persistence
mongoDB:

  # URL
  url: "mongodb://localhost:27017/parietal"

  # Name of collection containing networks
  networks: "networks"

  # Name of collection containing training data
  trainingData: "trainingData"


